name: jackpot
version: 0.1.0.0
github: Javran/jackpot
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2021 Javran Cheng"

description: description

dependencies:
- base
- array
- bytestring
- mtl
- scientific
- containers
- file-embed
- unordered-containers
- split

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  build-tools:  
    - happy
    - alex

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - jackpot
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - jackpot
      - QuickCheck
      - hspec
      - raw-strings-qq
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
